//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotas.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Versão 4.2 : Adicionado  Radio(Rota 1 e Rota 2)
Versão 4.2 : Adicionado  Checagem por senha antes de qualquer alteração(Padrao)
Versão 4.3 : Correção de BUG ao modificar Rotas( Rota 1 e Rota 2 não entrava nas modificações) Obrigado Davi.
Versão 4.3 : Instalação Automatica no Disco Local C:
Versão 4.3 :  Odenação da tabela de alteração por data. Obrigado Davi")]
        public string Versão {
            get {
                return ((string)(this["Versão"]));
            }
            set {
                this["Versão"] = value;
            }
        }
    }
}
